FROM node:14.4.0-alpine
WORKDIR /usr/src/app
RUN chmod -R 777 /usr/src/app

ENV NODE_ENV=production
COPY package.json .
COPY yarn.lock .

RUN npm install --production

COPY . .

EXPOSE 3000

RUN ls -sail

CMD [ "npm", "start" ]