const STATUS = {
    OPEN: "OPEN",
    CLOSED: "CLOSED"
};

const STAGE = {
    CALL: "CALL",
    INTERACTION: "INTERACTION",
    DOCUMENTING: "DOCUMENTING"
};

const TRANSITIONS = {
    CREATED: "CREATED",
    INTERACTION: "INTERACTION",
    DOCUMENTING: "DOCUMENTING",
    FAILED: "FAILED",
    SUBMISSION: "SUBMISSION"
};

export {
    STATUS,
    STAGE,
    TRANSITIONS
}