export const coreConfig = [
  {
    readableField: "Handler Email",
    internalField: "email",
    type: "string",
    checked: true,
    organization: null,
    campaignId: null,
  },
  {
    readableField: "Address",
    internalField: "address",
    type: "string",
    checked: true,
  },
  {
    readableField: "Amount",
    internalField: "amount",
    type: "number",
    checked: true,
  },
  {
    readableField: "City",
    internalField: "city",
    type: "string",
    checked: true,
  },
  {
    readableField: "Company",
    internalField: "companyName",
    type: "string",
    checked: true,
  },
  {
    readableField: "Customer Email",
    internalField: "customerEmail",
    group: "contact",
    type: "string",
    checked: true,
  },
  {
    readableField: "First Name",
    internalField: "firstName",
    type: "string",
    checked: true,
  },
  {
    readableField: "Last Name",
    internalField: "lastName",
    type: "string",
    checked: true,
  },
  {
    readableField: "Full Name",
    internalField: "fullName",
    type: "string",
    checked: true,
  },
  {
    readableField: "Lead Id",
    internalField: "externalId",
    type: "string",
    checked: true,
  },
  {
    readableField: "Lead Status",
    internalField: "leadStatus",
    type: "string",
    checked: true,
  },
  {
    readableField: "Mobile Phone",
    internalField: "mobilePhone",
    group: "contact",
    type: "tel",
    checked: true,
  },
  {
    readableField: "Pin Number",
    internalField: "pincode",
    type: "number",
    checked: true,
  },
  {
    readableField: "Lead Source",
    internalField: "source",
    type: "string",
    checked: true,
  },
  {
    readableField: "State",
    internalField: "state",
    type: "string",
    checked: true,
  },
  {
    readableField: "Follow Up",
    internalField: "followUp",
    type: "date",
    checked: true,
  },
];
