apiVersion: v1
data:
  BULL_APP_PORT: "3333"
  BULL_REDIS_PASSWORD: 6bYslLCEr7StUsoI8KDYcSYRZGsaBgkW
  BULL_REDIS_PORT: "11919"
  BULL_REDIS_URL: redis-11919.c90.us-east-1-3.ec2.cloud.redislabs.com
  MONGODB_URI: mongodb+srv://shanurrahman:VKOGz0Xe4O9Tc1Sj@molecule-dev.qaqbv.mongodb.net/molecule?retryWrites=true&w=majority
  VAPID_PRIVATE: 3-qnHIybXgG96FDuSQOyS0Vw6TZ5MGfD9N4h7ko6uU8
  VAPID_PUBLIC: BP-JCVX39AIlu8i_LYMghwFWMnXDRf2QD6nV9JL_SZOSi_ZfeYmTfvccBobaljNtpZbb5MaHMKdkM9N_fDX0uss
  accessKeyId: AKIARGBOXP35BONONB4J
  region: ap-south-1
  secretAccessKey: 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
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker-molecule_bull_microservice--env
  name: molecule_bull_microservice--env
